### ISSUE TITLE
F-2: Fix pages styling after migration to React

### ISSUE THREAD

**Issue by SescHustle** [SescHustle/emptypocket#10]
## Overview
After migration to ReactJS, the styles are broken. Need to fix pages layout and update the stylesheets.

## Requirements
- Bootstrap should be used for layout.
- Custom styles can be omitted if they are redundant.
- The page should look the same as before the migration (except for designs, maybe).
- The point is to simply display the page correctly, so design stylings can be removed and added later.

## Work plan
- [x] Add bootstrap and JQuery to the project
- [x] Identify correct way to add bootstrap classes to JSX code
- [x] Fix pages layout with bootstrap grid system
