### ISSUE TITLE
F-4: Toggle 'Add Spending' form on button click

### ISSUE THREAD

**Issue by SescHustle** [SescHustle/emptypocket#12]
## Overview
The form is temporary always displayed after migration to ReactJS. Need to implement the logic to show it only when `Add New` button is clicked (toggle it to `Cancel`), and close when a spending added on `Cancel` pressed.

## Requirements
- See the requirements in **Overview**

## Work plan
- [x] Implement `CancelButton` and `AddNew` buttons
- [x] Toggle the buttons and the form on click
- [x] Automatically toggle those when the form is sent
