### ISSUE TITLE
B-3: Add connection to a database

### ISSUE THREAD

**Issue by seschustle** [SescHustle/emptypocket#16]
### Overview
Currently, JSON files are used as a local database. Need to select some cloud database and use it instead.
### Requirements
No special requirements.
### Work plan
- [ ] Decide on which database to use (e.g. **Firebase**, **MongoDB** etc.)
- [ ] Add necessary dependencies to work with it
- [ ] Update configs
- [ ] Update existing Models to work with DB instead of local file
