### ISSUE TITLE
F-5: Homepage landing

### ISSUE THREAD

**Issue by seschustle** [SescHustle/emptypocket#17]
### Overview
Need to create a homepage landing which will describe the application purpose and features for new users.
### Requirements
1. Homepage should have a different header then other pages
2. Header must contain **login**, **register** or **profile** and **logout** links based on current user
3. Other header links should be just the anchors to certain content on the page.
4. Content should consists of various component types, such as cards, carousels, modals, accordions etc.
5. Homepage should be responsive
### Work plan
- [ ] Create homepage design
- [ ] Implement needed child components
- [ ] Update Header component (maybe divide it to several smaller components)
- [ ] Create the page itself
