### ISSUE TITLE
F-7: Redesign and styles update

### ISSUE THREAD

**Issue by seschustle** [SescHustle/emptypocket#19]
### Overview
Current design was created for temporary purposes, need to create a new nice one.
### Requirements
1. Need to create light and dark mode.
2. Other popular money tracking applications should be used as a reference for color schema.
### Work plan
- [ ] Research the references.
- [ ] Create light mode color schema.
- [ ] Create dark mode color schema.
- [ ] Create new CSS classes for updated designs
- [ ] Update footer navigation and socials
- [ ] Update other components stylings
