### ISSUE TITLE
F-8: Add routing

### ISSUE THREAD

**Issue by seschustle** [SescHustle/emptypocket#20]
### Overview
Need to add an ability to visit any pages based on client-side routing
### Requirements
1. Use **React Router** library
2. Need to add support for `/`, `/spendings`, `/incomes`, `/login`, and `/register` pages
### Work plan
- [ ] Investigate how react-router works
- [ ] Include react-router dependency
- [ ] Update current pages to use routing
