### ISSUE TITLE
B-4: User authorization support

### ISSUE THREAD

**Issue by seschustle** [SescHustle/emptypocket#21]
### Overview
Need to implement a backend part of user authorization.
### Requirements
1. Each user should have his unique string ID (which could be later user to add security for requests).
2. Validation should be resolved on backend.
4. Users should be saved into database.
5. At this moment, if would be sufficient to have next fields: `username`, `password` (hashed), `name`, `id` and `email` (optionally).
6. Register or login response should include name and id only.
### Work plan
- [ ] Add DB support for new entity if needed.
- [ ] Add validators for input fields.
- [ ] Compare input data to accept or reject login (find by username, then compare passwords).
