### ISSUE TITLE
F-9: Login and Registration pages

### ISSUE THREAD

**Issue by seschustle** [SescHustle/emptypocket#22]
### Overview
Need to add login and registration for users on frontend.
### Requirements
1. When unauthorized user tries to visit any page except home, he should be redirected to login page.
2. Pages should have link to each other.
3. The link to these pages should only be visible on homepage.
### Work plan
- [ ] Create login form and page
- [ ] Create registration form and page.
- [ ] Update other pages to interact with new ones (i.e redirect or show a link).
