### ISSUE TITLE
F-10: Authorization support

### ISSUE THREAD

**Issue by seschustle** [SescHustle/emptypocket#23]
### Overview
Authorized users should have a bit different interface then unauthorized, so need to update frontend to support this.
### Requirements
1. Profile and logout links should be shown instead login and register (profile is only shown for homepage).
2. Need to interact with backend on login or registration attempt.
3. When user is logged in or registered, need to redirect him to his profile.
4. When user is logged out, redirect him to the homepage.
### Work plan
- [ ] Registration support
- [ ] Logging in support
- [ ] Logging out support
- [ ] Update other page references to these pages.
