### ISSUE TITLE
F-1: Set up custom project build and dev mode

### ISSUE THREAD

**Issue by SescHustle** [SescHustle/emptypocket#6]
## Overview
Currently, `react-scripts` library is used to start up the app dev mode and build. Need to replace it with custom bundling (with webpack) and JS compiling (with babel).

## Requirements
- Use Webpack for bundling
- Live reload on file change is needed for development
- Babel should be used to translate JS syntax
- Scripts must support JSX and Sass

## Work plan
- [x] Install all necessary libraries with npm
- [x] Configure Webpack build
- [x] Configure development mode
