### ISSUE TITLE
B-1: Improve project structure 

### ISSUE THREAD

**Issue by SescHustle** [SescHustle/emptypocket#8]
## Overview
To keep the codebase clean, readable and convenient for development need to separate the different logic to a different parts of the project.

## Requirements
- Separate controllers, models and util parts
- The structure must be easy to extend

## Work plan
- [x] Create a folder for controllers
- [x] Create a folder for models
- [x] Create a folder for utility and helper classes
- [x] Extract existing logic to those folders
