### ISSUE TITLE
B-2: Implement spendings save

### ISSUE THREAD

**Issue by SescHustle** [SescHustle/emptypocket#9]
## Overview
Need to implement the ability to save spendings. Temporary, it can be done using simple JSON file as a local database.

## Requirements
- Need to be able to create new spending and get all spendings.
- The feature must follow the project structure.
- Response must be able to be processed on frontend.

## Work plan
- [x] Set up the connection with the file system to get local DB
- [x] Add `getAll` and `addNew` to spendings model
- [x] Implement `getAll` and `addNew` API routes in spendings controller
